# Generated by Django 2.1.2 on 2018-10-20 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField()),
                ('datetime', models.DateTimeField()),
            ],
            options={
                'ordering': ('datetime',),
            },
        ),
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
                ('device_id', models.CharField(max_length=30, unique=True)),
                ('unit', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='datarecord',
            name='data_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.DataSet'),
        ),
        migrations.AddField(
            model_name='datarecord',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Device'),
        ),
        migrations.AddIndex(
            model_name='datarecord',
            index=models.Index(fields=['datetime'], name='data_datare_datetim_420e97_idx'),
        ),
    ]
